{{- $name := include "servicenowautomation-mcp.fullname" . -}}

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "{{ $name }}-ap"
  labels:
    {{- include "servicenowautomation-mcp.labels" . | nindent 4 }}
spec:
  {{- include "servicenowautomation-mcp.authorizationPolicySpec" . | nindent 2 }}
    # to:
    # - operation:
    #     methods: ["GET"]
