{{- $name := include "servicenowautomation-mcp.fullname" . -}}
{{- $cfgname := printf "%s-%s" $name "config" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "servicenowautomation-mcp.fullname" . }}
  labels:
    {{- include "servicenowautomation-mcp.labels" . | nindent 4 }}
  annotations:
    ado_repo: {{ .Values.adoRepoName | quote}}
    ado_pipeline: {{ .Values.adoPipelineId | quote}}
    ado_buildId: {{ .Values.adoBuildId | quote}}
    ado_teamProject: {{ .Values.adoTeamProject | quote}}
    ado_commitId: {{ .Values.adoCommitId | quote}}
    ado_sourceBranchName: {{ .Values.adoSourceBranchName | quote}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "servicenowautomation-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        ado_repo: {{ .Values.adoRepoName | quote}}
        ado_pipeline: {{ .Values.adoPipelineId | quote}}
        ado_buildId: {{ .Values.adoBuildId | quote}}
        ado_teamProject: {{ .Values.adoTeamProject | quote}}
        ado_commitId: {{ .Values.adoCommitId | quote}}
        ado_sourceBranchName: {{ .Values.adoSourceBranchName | quote}}
        pipelines/org: {{ .Values.pipelineMetadata.org | quote }}
        pipelines/project: {{ .Values.pipelineMetadata.project | quote }}
        pipelines/pipeline: {{ .Values.pipelineMetadata.pipeline | quote }}
        pipelines/run: {{ .Values.pipelineMetadata.run | quote }}
        pipelines/build: {{ .Values.pipelineMetadata.build | quote }}
        pipelines/buildurl: {{ .Values.pipelineMetadata.buildUrl | quote }}
        pipelines/repositoryuri: {{ .Values.pipelineMetadata.repositoryUri | quote }}
        pipelines/sourcebranch: {{ .Values.pipelineMetadata.sourceBranch | quote }}
        pipelines/commitid: {{ .Values.pipelineMetadata.commitId | quote }}
      labels:
        {{- include "servicenowautomation-mcp.selectorLabels" . | nindent 8 }}
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - uvicorn
            - servicenow_mcp.server:mcp_app
            - --host
            - {{ .Values.mcp.args.host | quote }}
            - --port
            - {{ .Values.mcp.args.port | quote }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.inf.conf.environment | quote }}
            - name: PATH_BASE
              value: "{{ .Values.pathBase }}-{{ .Values.inf.conf.environment }}"
          envFrom:
            - configMapRef:
                name: {{ $cfgname }}
            {{- if .Values.secretEnv.existingSecret }}
            - secretRef:
                name: {{ .Values.secretEnv.existingSecret | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.mcp.args.port }}
              protocol: TCP
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsConfig:
        options:
          - name: ndots
            value: "1"
          - name: single-request
