{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "servicenowautomation-mcp.labels" . | nindent 4 }}
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: {{ .Values.inf.conf.msi_clientid }}
{{- end }}